update package scripts (#300)
Updates for convex 1.35

- update package scripts to use `--start`, dropping `run-p` and `file-exists` to simplify
- update convex.json codegen default (can remove)
- add ai-files
- add http example

diff --git a/template-component/.github/workflows/test.yml b/template-component/.github/workflows/test.yml
--- a/template-component/.github/workflows/test.yml
+++ b/template-component/.github/workflows/test.yml
@@ -30,7 +30,7 @@ jobs:
           npm i
           npm run build
       - name: Publish package for testing branch
-        run: npx pkg-pr-new publish || echo "Have you set up pkg-pr-new for this repo?"
+        run: npx pkg-pr-new publish || echo "pkg-pr-new failed"
       - name: Test
         run: |
           npm run test
